#!/usr/bin/env python3
"""AI工程实践文档第三批扩充 - 补充约280行"""
import os

DOC = os.path.join(os.path.dirname(__file__), "..", "docs", "engineering-practice",
                   "AI工程实践完整知识体系深度解析.md")
MARKER = "## 参考资源"

lines = []
lines.append("")
lines.append("")
lines.append("## 附录H AI工程常见故障与排查指南")
lines.append("")
lines.append("### H.1 LLM调用类故障")
lines.append("")
lines.append("| 故障现象 | 可能原因 | 排查步骤 | 解决方案 |")
lines.append("|---------|---------|---------|---------|")
lines.append("| 429 Too Many Requests | 触发速率限制 | 检查请求频率和并发数 | 退避重试+请求队列 |")
lines.append("| 504 Gateway Timeout | LLM推理超时 | 检查输入长度和模型负载 | 减少输入+设置超时 |")
lines.append("| 输出格式错误 | JSON解析失败 | 检查prompt约束是否明确 | 用JSON Schema+重试 |")
lines.append("| 回答质量突降 | 模型版本更新/prompt退化 | 对比历史评测结果 | 锁定模型版本+回滚prompt |")
lines.append("| Token超限 | 上下文超过窗口 | 检查实际token数 | 压缩上下文+分层记忆 |")
lines.append("| 幻觉增多 | 上下文不足/模型不确定 | 检查检索召回率 | 优化RAG+加强grounding |")
lines.append("| 响应为空 | 安全过滤误拦截 | 查看API返回的finish_reason | 调整安全阈值 |")
lines.append("| 成本飙升 | Token泄漏/循环调用 | 查看每次调用的token用量 | 限制循环次数+设预算上限 |")
lines.append("")
lines.append("### H.2 RAG系统故障")
lines.append("")
lines.append("| 故障现象 | 可能原因 | 排查步骤 | 解决方案 |")
lines.append("|---------|---------|---------|---------|")
lines.append("| 检索不到相关文档 | Embedding质量差 | 检查查询向量相似度分布 | 换Embedding模型+查询改写 |")
lines.append("| 检索到但不相关 | chunk切分不当 | 检查Top-K文档内容 | 调整chunk大小+加元数据 |")
lines.append("| 回答与文档矛盾 | LLM未充分利用上下文 | 检查prompt中context位置 | 优化prompt+强调引用 |")
lines.append("| 检索延迟高 | 向量库性能问题 | 检查向量库指标和查询计划 | 优化索引+缓存热数据 |")
lines.append("| 新文档未被检索 | 索引未更新 | 检查增量索引管道 | 修复索引管道+触发重建 |")
lines.append("| 跨文档推理失败 | 单chunk信息不足 | 检查相关chunk是否被召回 | 增大chunk+多跳检索 |")
lines.append("")
lines.append("### H.3 Agent系统故障")
lines.append("")
lines.append("| 故障现象 | 可能原因 | 排查步骤 | 解决方案 |")
lines.append("|---------|---------|---------|---------|")
lines.append("| Agent无限循环 | 工具返回值不满足退出条件 | 查看循环中每步的状态变化 | 加最大循环限制+改退出逻辑 |")
lines.append("| 工具选择错误 | 工具描述不清或功能重叠 | 对比工具描述和实际选择 | 优化工具描述+减少工具数 |")
lines.append("| 参数构造错误 | LLM对参数格式理解错误 | 检查工具schema和实际参数 | 加few-shot示例+参数校验 |")
lines.append("| 跨步骤状态丢失 | 上下文管理不当 | 检查状态传递链路 | 显式状态持久化 |")
lines.append("| 并发工具调用冲突 | 工具间有隐含依赖 | 分析工具调用时序 | 声明依赖关系+顺序执行 |")
lines.append("")
lines.append("")
lines.append("## 附录I 生产环境Checklist")
lines.append("")
lines.append("### I.1 上线前检查清单")
lines.append("")
lines.append("**功能质量**")
lines.append("- [ ] 核心场景评测通过率 > 85%")
lines.append("- [ ] 边界case覆盖测试完成")
lines.append("- [ ] 安全性红队测试通过")
lines.append("- [ ] 幻觉率 < 5% (关键场景 < 1%)")
lines.append("- [ ] 用户验收测试通过")
lines.append("")
lines.append("**性能指标**")
lines.append("- [ ] P95延迟 < 目标值")
lines.append("- [ ] 并发压测通过")
lines.append("- [ ] 内存/GPU资源无泄漏")
lines.append("- [ ] 长时间运行稳定性测试通过")
lines.append("")
lines.append("**安全合规**")
lines.append("- [ ] 提示注入防御已部署并测试")
lines.append("- [ ] 输出安全过滤已启用")
lines.append("- [ ] 敏感数据处理符合隐私规范")
lines.append("- [ ] 工具权限矩阵已配置")
lines.append("- [ ] 审计日志已启用")
lines.append("")
lines.append("**可靠性**")
lines.append("- [ ] LLM调用重试和fallback已配置")
lines.append("- [ ] 全局超时已设置")
lines.append("- [ ] 熔断器已配置")
lines.append("- [ ] 限流策略已设置")
lines.append("- [ ] 回滚方案已验证")
lines.append("")
lines.append("**监控告警**")
lines.append("- [ ] 核心指标监控已配置")
lines.append("- [ ] 告警规则和oncall已设置")
lines.append("- [ ] Trace链路追踪已接入")
lines.append("- [ ] 成本监控和预算告警已设置")
lines.append("")
lines.append("**部署运维**")
lines.append("- [ ] CI/CD流水线已配置")
lines.append("- [ ] 灰度发布策略已定义")
lines.append("- [ ] 回滚操作已演练")
lines.append("- [ ] 文档(架构图/操作手册/FAQ)已完成")
lines.append("")
lines.append("")
lines.append("## 附录J AI工程项目模板")
lines.append("")
lines.append("### J.1 AI项目目录结构")
lines.append("")
lines.append("```")
lines.append("my-ai-project/")
lines.append("├── src/")
lines.append("│   ├── agents/          # Agent定义和编排")
lines.append("│   │   ├── main_agent.py")
lines.append("│   │   └── sub_agents/")
lines.append("│   ├── tools/           # 工具/函数定义")
lines.append("│   │   ├── search.py")
lines.append("│   │   └── database.py")
lines.append("│   ├── prompts/         # Prompt模板")
lines.append("│   │   ├── system.md")
lines.append("│   │   └── templates/")
lines.append("│   ├── retrievers/      # RAG检索器")
lines.append("│   │   ├── vector_store.py")
lines.append("│   │   └── reranker.py")
lines.append("│   ├── safety/          # 安全过滤")
lines.append("│   │   ├── input_filter.py")
lines.append("│   │   └── output_filter.py")
lines.append("│   ├── models/          # 数据模型")
lines.append("│   │   └── schemas.py")
lines.append("│   └── utils/           # 工具函数")
lines.append("│       ├── llm_client.py")
lines.append("│       └── cache.py")
lines.append("├── tests/")
lines.append("│   ├── unit/            # 单元测试")
lines.append("│   ├── integration/     # 集成测试")
lines.append("│   ├── evals/           # AI评估")
lines.append("│   │   ├── datasets/    # 评估数据集")
lines.append("│   │   └── run_eval.py")
lines.append("│   └── safety/          # 安全测试")
lines.append("├── configs/")
lines.append("│   ├── models.yaml      # 模型配置")
lines.append("│   ├── prompts.yaml     # Prompt版本")
lines.append("│   └── tools.yaml       # 工具配置")
lines.append("├── scripts/")
lines.append("│   ├── index_docs.py    # 文档索引脚本")
lines.append("│   └── run_eval.sh      # 评估运行脚本")
lines.append("├── docs/")
lines.append("│   ├── architecture.md  # 架构设计")
lines.append("│   └── runbook.md       # 运维手册")
lines.append("├── docker-compose.yml")
lines.append("├── Dockerfile")
lines.append("├── pyproject.toml")
lines.append("└── README.md")
lines.append("```")
lines.append("")
lines.append("### J.2 模型配置管理")
lines.append("")
lines.append("```yaml")
lines.append("# configs/models.yaml")
lines.append("llm:")
lines.append("  primary:")
lines.append("    provider: openai")
lines.append("    model: gpt-4o")
lines.append("    temperature: 0.1")
lines.append("    max_tokens: 4096")
lines.append("    timeout: 30")
lines.append("    max_retries: 3")
lines.append("  fallback:")
lines.append("    provider: anthropic")
lines.append("    model: claude-3-5-sonnet")
lines.append("    temperature: 0.1")
lines.append("    max_tokens: 4096")
lines.append("  routing:")
lines.append("    simple_tasks: gpt-4o-mini")
lines.append("    complex_tasks: gpt-4o")
lines.append("    code_generation: claude-3-5-sonnet")
lines.append("")
lines.append("embedding:")
lines.append("  model: BAAI/bge-m3")
lines.append("  dimension: 1024")
lines.append("  batch_size: 32")
lines.append("")
lines.append("safety:")
lines.append("  input_max_length: 4096")
lines.append("  max_agent_loops: 10")
lines.append("  require_approval_tools:")
lines.append("    - send_email")
lines.append("    - execute_code")
lines.append("    - modify_database")
lines.append("```")
lines.append("")
lines.append("### J.3 Prompt模板规范")
lines.append("")
lines.append("```markdown")
lines.append("# prompts/system.md")
lines.append("# Version: 2.3.1")
lines.append("# Last updated: 2024-12-01")
lines.append("# Eval score: 4.2/5 (n=500)")
lines.append("")
lines.append("你是一个专业的客服助手。")
lines.append("")
lines.append("## 能力范围")
lines.append("- 查询订单状态")
lines.append("- 处理退款申请")
lines.append("- 回答产品问题")
lines.append("")
lines.append("## 行为准则")
lines.append("- 始终基于检索到的信息回答，不要编造")
lines.append("- 如果不确定，告知用户并转接人工")
lines.append("- 涉及资金操作需要用户二次确认")
lines.append("- 不回答与业务无关的问题")
lines.append("")
lines.append("## 输出格式")
lines.append("使用友好的中文回答。需要调用工具时，按规定格式输出。")
lines.append("```")
lines.append("")
lines.append("")
lines.append("---")
lines.append("")

CONTENT = "\n".join(lines)

with open(DOC, "r", encoding="utf-8") as f:
    content = f.read()

if MARKER in content:
    content = content.replace(MARKER, CONTENT + "\n" + MARKER, 1)
else:
    content += CONTENT

with open(DOC, "w", encoding="utf-8") as f:
    f.write(content)

import subprocess
result = subprocess.run(["wc", "-l", DOC], capture_output=True, text=True)
print(f"当前行数: {result.stdout.strip()}")
