#!/usr/bin/env python3
"""AI工程实践文档第二批扩充 - 补充约580行"""
import os

DOC = os.path.join(os.path.dirname(__file__), "..", "docs", "engineering-practice",
                   "AI工程实践完整知识体系深度解析.md")
MARKER = "## 参考资源"

lines = []
lines.append("")
lines.append("")
lines.append("## 十四、AI应用安全工程")
lines.append("")
lines.append("### 14.1 LLM应用安全威胁模型（OWASP Top 10 for LLM）")
lines.append("")
lines.append("| 排名 | 威胁 | 描述 | 缓解措施 |")
lines.append("|------|------|------|---------|")
lines.append("| 1 | 提示注入 | 通过恶意输入操纵LLM行为 | 多层过滤+输入输出验证 |")
lines.append("| 2 | 不安全输出处理 | LLM输出未经验证直接使用 | 输出校验+消毒 |")
lines.append("| 3 | 训练数据投毒 | 恶意数据影响模型行为 | 数据审核+溯源 |")
lines.append("| 4 | 拒绝服务 | 构造高资源消耗请求 | 限流+输入长度限制 |")
lines.append("| 5 | 供应链漏洞 | 依赖的模型/库存在漏洞 | 供应链安全扫描 |")
lines.append("| 6 | 敏感信息泄露 | LLM输出训练数据中的敏感信息 | DP训练+输出过滤 |")
lines.append("| 7 | 不安全插件设计 | 工具/插件权限过大 | 最小权限+审计 |")
lines.append("| 8 | 过度代理 | Agent获得超出必要的操作权限 | 权限矩阵+HITL |")
lines.append("| 9 | 过度依赖 | 用户盲目信任AI输出 | 置信度显示+免责声明 |")
lines.append("| 10 | 模型窃取 | 通过API查询推断模型参数 | 速率限制+水印 |")
lines.append("")
lines.append("### 14.2 输入安全防护")
lines.append("")
lines.append("```python")
lines.append("class InputSanitizer:")
lines.append('    """LLM应用输入安全过滤器"""')
lines.append("")
lines.append("    def __init__(self):")
lines.append("        self.max_input_length = 4096")
lines.append("        self.injection_patterns = [")
lines.append('            r"ignore (all |previous |above )?instructions",')
lines.append('            r"you are now",')
lines.append('            r"system prompt",')
lines.append('            r"reveal your",')
lines.append('            r"\\[INST\\]",')
lines.append('            r"<\\|im_start\\|>",')
lines.append("        ]")
lines.append("")
lines.append("    def sanitize(self, user_input: str) -> tuple[str, bool]:")
lines.append('        """返回 (清理后的输入, 是否安全)"""')
lines.append("        # 1. 长度检查")
lines.append("        if len(user_input) > self.max_input_length:")
lines.append("            return user_input[:self.max_input_length], True")
lines.append("")
lines.append("        # 2. 模式匹配检测")
lines.append("        import re")
lines.append("        for pattern in self.injection_patterns:")
lines.append("            if re.search(pattern, user_input, re.IGNORECASE):")
lines.append("                return user_input, False  # 标记不安全")
lines.append("")
lines.append("        # 3. 特殊字符清理")
lines.append("        # 移除可能干扰prompt结构的控制字符")
lines.append("        cleaned = user_input.replace('\\x00', '')")
lines.append("")
lines.append("        return cleaned, True")
lines.append("```")
lines.append("")
lines.append("### 14.3 输出安全过滤")
lines.append("")
lines.append("```")
lines.append("输出安全过滤管道:")
lines.append("")
lines.append("  LLM原始输出")
lines.append("      |")
lines.append("  1. PII检测与脱敏")
lines.append("  ├─ 姓名/手机/身份证/银行卡")
lines.append("  └─ 使用NER模型或正则匹配")
lines.append("      |")
lines.append("  2. 有害内容检测")
lines.append("  ├─ 分类器检测(toxicity/violence/self-harm)")
lines.append("  └─ 关键词黑名单")
lines.append("      |")
lines.append("  3. 幻觉检测")
lines.append("  ├─ 与检索到的事实对比")
lines.append("  └─ 一致性校验")
lines.append("      |")
lines.append("  4. 格式验证")
lines.append("  ├─ JSON Schema校验")
lines.append("  └─ 业务逻辑校验")
lines.append("      |")
lines.append("  安全输出 -> 返回用户")
lines.append("```")
lines.append("")
lines.append("")
lines.append("## 十五、AI产品工程化实践")
lines.append("")
lines.append("### 15.1 AI产品设计原则")
lines.append("")
lines.append("| 原则 | 含义 | 实践方法 |")
lines.append("|------|------|---------|")
lines.append("| 设定正确期望 | 用户知道AI的能力边界 | 明确告知AI局限性 |")
lines.append("| 优雅降级 | AI失败时仍有可用方案 | 回退到规则/人工 |")
lines.append("| 可控性 | 用户能纠正和引导AI | 反馈机制/编辑能力 |")
lines.append("| 透明性 | 用户理解AI做了什么 | 展示推理过程/引用来源 |")
lines.append("| 渐进式信任 | 从低风险场景开始 | 分阶段上线 |")
lines.append("| 持续学习 | 从用户反馈中改进 | 反馈收集/效果追踪 |")
lines.append("")
lines.append("### 15.2 AI功能的A/B测试设计")
lines.append("")
lines.append("```")
lines.append("AI功能A/B测试特殊考量:")
lines.append("")
lines.append("1. 指标设计")
lines.append("├─ 主指标: 任务成功率/用户满意度")
lines.append("├─ 护栏指标: 错误率/安全事件/成本")
lines.append("└─ 辅助指标: 使用时长/重试率/放弃率")
lines.append("")
lines.append("2. 样本量估算")
lines.append("├─ AI输出的方差通常大于传统功能")
lines.append("├─ 需要更多样本才能达到统计显著性")
lines.append("└─ 推荐: 至少每组1000次完整交互")
lines.append("")
lines.append("3. 分流策略")
lines.append("├─ 按用户分流(非按请求): 保证体验一致")
lines.append("├─ 新用户/老用户分开分析")
lines.append("└─ 考虑用户对AI能力的不同预期")
lines.append("")
lines.append("4. 结果分析")
lines.append("├─ 不仅看平均值，关注分布")
lines.append("├─ 分析失败case的模式")
lines.append("├─ LLM输出的多样性影响评估")
lines.append("└─ 长期效果 vs 新鲜感效应")
lines.append("```")
lines.append("")
lines.append("### 15.3 用户反馈系统设计")
lines.append("")
lines.append("| 反馈类型 | 收集方式 | 应用场景 |")
lines.append("|---------|---------|---------|")
lines.append("| 显式正面 | 点赞/5星评分 | 标注优质回答 |")
lines.append("| 显式负面 | 点踩+原因选择 | 定位具体问题类型 |")
lines.append("| 显式纠正 | 用户编辑AI输出 | 高价值训练数据 |")
lines.append("| 隐式正面 | 采纳建议/复制回答 | 间接满意度信号 |")
lines.append("| 隐式负面 | 重试/换提问方式/放弃 | 间接不满信号 |")
lines.append("| 对话级 | 会话结束评分 | 整体体验评估 |")
lines.append("")
lines.append("")
lines.append("## 十六、AI工程最佳实践总结")
lines.append("")
lines.append("### 16.1 LLM应用开发 Do's and Don'ts")
lines.append("")
lines.append("**DO (推荐)**：")
lines.append("")
lines.append("- 先做可行性POC，验证LLM能否胜任")
lines.append("- 建立评估数据集，在写代码之前先定义成功标准")
lines.append("- 用结构化输出约束LLM")
lines.append("- System prompt与业务逻辑分离")
lines.append("- 所有LLM调用都加超时和重试")
lines.append("- 监控token消耗和成本")
lines.append("- 关键操作加人工审核")
lines.append("- 记录完整的请求/响应日志用于调试")
lines.append("- 从简单架构开始，按需增加复杂度")
lines.append("- 保持prompt简洁明确")
lines.append("")
lines.append("**DON'T (避免)**：")
lines.append("")
lines.append("- 不要假设LLM的输出是确定性的")
lines.append("- 不要把整个数据库dump进上下文")
lines.append("- 不要让Agent无限循环")
lines.append("- 不要把用户输入直接拼接到system prompt")
lines.append("- 不要忽视成本——一个bug可能烧掉几千美元")
lines.append("- 不要用Demo的标准衡量生产系统")
lines.append("- 不要跳过评估直接上线")
lines.append("- 不要用单一指标评估AI系统")
lines.append("- 不要过度工程化——先让它工作，再让它优雅")
lines.append("- 不要忽视安全——提示注入是真实威胁")
lines.append("")
lines.append("### 16.2 AI工程成熟度自评表")
lines.append("")
lines.append("| 维度 | Level 1 (基础) | Level 2 (规范) | Level 3 (成熟) | Level 4 (卓越) |")
lines.append("|------|--------------|--------------|--------------|--------------|")
lines.append("| Prompt管理 | 硬编码 | 模板化+版本 | A/B测试+自动优化 | 数据驱动迭代 |")
lines.append("| 评估体系 | 手动测试 | 基础测试集 | 自动化评估+CI集成 | 在线评估+反馈闭环 |")
lines.append("| 可观测性 | 打日志 | 结构化日志 | Trace+指标+告警 | 全链路+根因分析 |")
lines.append("| 安全 | 基本过滤 | 多层防御 | 红队测试+持续监控 | 自动化安全闭环 |")
lines.append("| 成本 | 不关注 | 有监控 | 有优化策略 | 自动化成本控制 |")
lines.append("| 部署 | 手动 | 脚本化 | CI/CD+灰度 | 自动化+秒级回滚 |")
lines.append("| 数据管理 | 静态 | 手动更新 | 自动化管道 | 实时+增量更新 |")
lines.append("| 可靠性 | 无容错 | 基本重试 | 熔断+降级+冗余 | 混沌工程验证 |")
lines.append("")
lines.append("")
lines.append("## 附录E AI工程关键数据参考")
lines.append("")
lines.append("| 指标 | 参考值 | 说明 |")
lines.append("|------|--------|------|")
lines.append("| LLM API调用延迟(P50) | 0.5-2s | 取决于模型和输出长度 |")
lines.append("| LLM API调用延迟(P99) | 3-15s | 取决于模型和负载 |")
lines.append("| RAG检索延迟 | 50-200ms | 向量检索+重排序 |")
lines.append("| 用户可接受等待 | 3-10s | 对话场景 |")
lines.append("| 语义缓存命中率 | 20-60% | 取决于场景 |")
lines.append("| GPT-4o成本 | 输入$2.5/输出$10 per 1M tokens | 2024价格 |")
lines.append("| GPT-4o-mini成本 | 输入$0.15/输出$0.6 per 1M tokens | 2024价格 |")
lines.append("| Claude Sonnet成本 | 输入$3/输出$15 per 1M tokens | 2024价格 |")
lines.append("| H100单卡推理吞吐(70B) | 40-80 tokens/s | FP16 |")
lines.append("| INT4量化加速比 | 3-5x | 相对FP16 |")
lines.append("| BGE-M3 Embedding延迟 | 5-20ms | 单条文本 |")
lines.append("| Milvus检索延迟(1M向量) | 1-5ms | HNSW索引 |")
lines.append("")
lines.append("")
lines.append("## 附录F AI工程技术雷达（2024-2025）")
lines.append("")
lines.append("### 采纳 (Adopt)")
lines.append("")
lines.append("| 技术 | 类别 | 说明 |")
lines.append("|------|------|------|")
lines.append("| RAG | 架构 | LLM知识增强的标准方案 |")
lines.append("| 结构化输出 | 工程 | JSON Schema/Pydantic约束LLM输出 |")
lines.append("| 向量数据库 | 基础设施 | Embedding存储和检索的标配 |")
lines.append("| LLM可观测性 | 运维 | LangSmith/Langfuse已成标配 |")
lines.append("| Prompt版本管理 | 工程 | 配置化管理+回归测试 |")
lines.append("")
lines.append("### 试验 (Trial)")
lines.append("")
lines.append("| 技术 | 类别 | 说明 |")
lines.append("|------|------|------|")
lines.append("| Agent框架(LangGraph) | 架构 | 复杂任务编排趋于成熟 |")
lines.append("| MCP协议 | 标准 | 工具集成的统一协议 |")
lines.append("| GraphRAG | 架构 | 知识图谱增强RAG |")
lines.append("| LLM-as-Judge | 评估 | 用LLM评估LLM输出 |")
lines.append("| 投机解码 | 优化 | 加速推理不损精度 |")
lines.append("")
lines.append("### 评估 (Assess)")
lines.append("")
lines.append("| 技术 | 类别 | 说明 |")
lines.append("|------|------|------|")
lines.append("| 多模态Agent | 架构 | 视觉+语言+操作 |")
lines.append("| 端侧LLM | 部署 | 本地推理保护隐私 |")
lines.append("| 自动Prompt优化 | 工程 | DSPy等自动化方案 |")
lines.append("| Computer Use | Agent | 操作GUI完成任务 |")
lines.append("| AI编码Agent | 开发 | Devin/Codex类工具 |")
lines.append("")
lines.append("### 暂缓 (Hold)")
lines.append("")
lines.append("| 技术 | 类别 | 说明 |")
lines.append("|------|------|------|")
lines.append("| 无限自主Agent | 架构 | 可靠性和安全性不足 |")
lines.append("| 纯LLM无RAG方案 | 架构 | 幻觉问题严重 |")
lines.append("| 过度复杂多Agent | 架构 | 调试和维护成本太高 |")
lines.append("")
lines.append("")
lines.append("## 附录G 推荐阅读与学习资源")
lines.append("")
lines.append("### 书籍")
lines.append("")
lines.append("| 书名 | 作者 | 推荐原因 |")
lines.append("|------|------|---------|")
lines.append("| Designing Machine Learning Systems | Chip Huyen | ML系统设计经典 |")
lines.append("| Building LLM Apps | Various | LLM应用开发实战 |")
lines.append("| Machine Learning Engineering | Andriy Burkov | ML工程全景 |")
lines.append("| Reliable Machine Learning | Cathy Chen et al. | ML可靠性工程 |")
lines.append("")
lines.append("### 在线课程")
lines.append("")
lines.append("| 课程 | 平台 | 内容 |")
lines.append("|------|------|------|")
lines.append("| Full Stack LLM Bootcamp | FSDL | LLM全栈开发 |")
lines.append("| LLM Engineering | DeepLearning.AI | LLM工程化 |")
lines.append("| MLOps Specialization | Coursera | MLOps体系 |")
lines.append("| Stanford CS329S | Stanford | ML系统设计 |")
lines.append("")
lines.append("### 技术博客与资源")
lines.append("")
lines.append("| 资源 | 类型 | 关注点 |")
lines.append("|------|------|--------|")
lines.append("| Chip Huyen Blog | 博客 | ML系统/LLM工程 |")
lines.append("| Eugene Yan Blog | 博客 | RecSys/ML工程 |")
lines.append("| The Batch (Andrew Ng) | Newsletter | AI行业动态 |")
lines.append("| Simon Willison Blog | 博客 | LLM实践/工具 |")
lines.append("| LangChain Blog | 博客 | Agent/RAG最新实践 |")
lines.append("| Anthropic Blog | 博客 | LLM安全/对齐 |")
lines.append("| Latent Space Podcast | Podcast | AI工程深度访谈 |")
lines.append("")
lines.append("")
lines.append("---")
lines.append("")

CONTENT = "\n".join(lines)

with open(DOC, "r", encoding="utf-8") as f:
    content = f.read()

if MARKER in content:
    content = content.replace(MARKER, CONTENT + "\n" + MARKER, 1)
else:
    content += CONTENT

with open(DOC, "w", encoding="utf-8") as f:
    f.write(content)

import subprocess
result = subprocess.run(["wc", "-l", DOC], capture_output=True, text=True)
print(f"当前行数: {result.stdout.strip()}")
